[project]
name = "lab-test-file-uplouder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosmtpd>=1.4.6",
    "aiosmtplib>=5.0.0",
    "boto3>=1.42.5",
    "python-dotenv>=1.2.1",
]
